/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TanyaIndexRouteImport } from './routes/tanya/index'
import { Route as InteraktifIndexRouteImport } from './routes/interaktif/index'
import { Route as BerkasIndexRouteImport } from './routes/berkas/index'
import { Route as TanyaForumRouteImport } from './routes/tanya/forum'
import { Route as TanyaChatbotRouteImport } from './routes/tanya/chatbot'
import { Route as InteraktifGameRouteImport } from './routes/interaktif/game'
import { Route as InteraktifDukunganRouteImport } from './routes/interaktif/dukungan'
import { Route as BerkasPaparanRouteImport } from './routes/berkas/paparan'
import { Route as BerkasMakalahRouteImport } from './routes/berkas/makalah'
import { Route as BerkasLaporanRouteImport } from './routes/berkas/laporan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TanyaIndexRoute = TanyaIndexRouteImport.update({
  id: '/tanya/',
  path: '/tanya/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteraktifIndexRoute = InteraktifIndexRouteImport.update({
  id: '/interaktif/',
  path: '/interaktif/',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasIndexRoute = BerkasIndexRouteImport.update({
  id: '/berkas/',
  path: '/berkas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TanyaForumRoute = TanyaForumRouteImport.update({
  id: '/tanya/forum',
  path: '/tanya/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const TanyaChatbotRoute = TanyaChatbotRouteImport.update({
  id: '/tanya/chatbot',
  path: '/tanya/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const InteraktifGameRoute = InteraktifGameRouteImport.update({
  id: '/interaktif/game',
  path: '/interaktif/game',
  getParentRoute: () => rootRouteImport,
} as any)
const InteraktifDukunganRoute = InteraktifDukunganRouteImport.update({
  id: '/interaktif/dukungan',
  path: '/interaktif/dukungan',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasPaparanRoute = BerkasPaparanRouteImport.update({
  id: '/berkas/paparan',
  path: '/berkas/paparan',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasMakalahRoute = BerkasMakalahRouteImport.update({
  id: '/berkas/makalah',
  path: '/berkas/makalah',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasLaporanRoute = BerkasLaporanRouteImport.update({
  id: '/berkas/laporan',
  path: '/berkas/laporan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/berkas/laporan': typeof BerkasLaporanRoute
  '/berkas/makalah': typeof BerkasMakalahRoute
  '/berkas/paparan': typeof BerkasPaparanRoute
  '/interaktif/dukungan': typeof InteraktifDukunganRoute
  '/interaktif/game': typeof InteraktifGameRoute
  '/tanya/chatbot': typeof TanyaChatbotRoute
  '/tanya/forum': typeof TanyaForumRoute
  '/berkas/': typeof BerkasIndexRoute
  '/interaktif/': typeof InteraktifIndexRoute
  '/tanya/': typeof TanyaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/berkas/laporan': typeof BerkasLaporanRoute
  '/berkas/makalah': typeof BerkasMakalahRoute
  '/berkas/paparan': typeof BerkasPaparanRoute
  '/interaktif/dukungan': typeof InteraktifDukunganRoute
  '/interaktif/game': typeof InteraktifGameRoute
  '/tanya/chatbot': typeof TanyaChatbotRoute
  '/tanya/forum': typeof TanyaForumRoute
  '/berkas': typeof BerkasIndexRoute
  '/interaktif': typeof InteraktifIndexRoute
  '/tanya': typeof TanyaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/berkas/laporan': typeof BerkasLaporanRoute
  '/berkas/makalah': typeof BerkasMakalahRoute
  '/berkas/paparan': typeof BerkasPaparanRoute
  '/interaktif/dukungan': typeof InteraktifDukunganRoute
  '/interaktif/game': typeof InteraktifGameRoute
  '/tanya/chatbot': typeof TanyaChatbotRoute
  '/tanya/forum': typeof TanyaForumRoute
  '/berkas/': typeof BerkasIndexRoute
  '/interaktif/': typeof InteraktifIndexRoute
  '/tanya/': typeof TanyaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/berkas/laporan'
    | '/berkas/makalah'
    | '/berkas/paparan'
    | '/interaktif/dukungan'
    | '/interaktif/game'
    | '/tanya/chatbot'
    | '/tanya/forum'
    | '/berkas/'
    | '/interaktif/'
    | '/tanya/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/berkas/laporan'
    | '/berkas/makalah'
    | '/berkas/paparan'
    | '/interaktif/dukungan'
    | '/interaktif/game'
    | '/tanya/chatbot'
    | '/tanya/forum'
    | '/berkas'
    | '/interaktif'
    | '/tanya'
  id:
    | '__root__'
    | '/'
    | '/berkas/laporan'
    | '/berkas/makalah'
    | '/berkas/paparan'
    | '/interaktif/dukungan'
    | '/interaktif/game'
    | '/tanya/chatbot'
    | '/tanya/forum'
    | '/berkas/'
    | '/interaktif/'
    | '/tanya/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BerkasLaporanRoute: typeof BerkasLaporanRoute
  BerkasMakalahRoute: typeof BerkasMakalahRoute
  BerkasPaparanRoute: typeof BerkasPaparanRoute
  InteraktifDukunganRoute: typeof InteraktifDukunganRoute
  InteraktifGameRoute: typeof InteraktifGameRoute
  TanyaChatbotRoute: typeof TanyaChatbotRoute
  TanyaForumRoute: typeof TanyaForumRoute
  BerkasIndexRoute: typeof BerkasIndexRoute
  InteraktifIndexRoute: typeof InteraktifIndexRoute
  TanyaIndexRoute: typeof TanyaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanya/': {
      id: '/tanya/'
      path: '/tanya'
      fullPath: '/tanya/'
      preLoaderRoute: typeof TanyaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interaktif/': {
      id: '/interaktif/'
      path: '/interaktif'
      fullPath: '/interaktif/'
      preLoaderRoute: typeof InteraktifIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/': {
      id: '/berkas/'
      path: '/berkas'
      fullPath: '/berkas/'
      preLoaderRoute: typeof BerkasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanya/forum': {
      id: '/tanya/forum'
      path: '/tanya/forum'
      fullPath: '/tanya/forum'
      preLoaderRoute: typeof TanyaForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanya/chatbot': {
      id: '/tanya/chatbot'
      path: '/tanya/chatbot'
      fullPath: '/tanya/chatbot'
      preLoaderRoute: typeof TanyaChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interaktif/game': {
      id: '/interaktif/game'
      path: '/interaktif/game'
      fullPath: '/interaktif/game'
      preLoaderRoute: typeof InteraktifGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interaktif/dukungan': {
      id: '/interaktif/dukungan'
      path: '/interaktif/dukungan'
      fullPath: '/interaktif/dukungan'
      preLoaderRoute: typeof InteraktifDukunganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/paparan': {
      id: '/berkas/paparan'
      path: '/berkas/paparan'
      fullPath: '/berkas/paparan'
      preLoaderRoute: typeof BerkasPaparanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/makalah': {
      id: '/berkas/makalah'
      path: '/berkas/makalah'
      fullPath: '/berkas/makalah'
      preLoaderRoute: typeof BerkasMakalahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas/laporan': {
      id: '/berkas/laporan'
      path: '/berkas/laporan'
      fullPath: '/berkas/laporan'
      preLoaderRoute: typeof BerkasLaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BerkasLaporanRoute: BerkasLaporanRoute,
  BerkasMakalahRoute: BerkasMakalahRoute,
  BerkasPaparanRoute: BerkasPaparanRoute,
  InteraktifDukunganRoute: InteraktifDukunganRoute,
  InteraktifGameRoute: InteraktifGameRoute,
  TanyaChatbotRoute: TanyaChatbotRoute,
  TanyaForumRoute: TanyaForumRoute,
  BerkasIndexRoute: BerkasIndexRoute,
  InteraktifIndexRoute: InteraktifIndexRoute,
  TanyaIndexRoute: TanyaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
